server:
  port: 9094

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfile
      username: bilgeUser
      password: bilgeUser*
 # elasticsearch:
  #  uris: http://localhost:9200
  #  username: admin
   # password: root

logging:
  level:
    org.springframework: info
    com.example: info