server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/GokceLal/Java13ConfigServer.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "GokceLal"
          password: ${GIT_KEY} #bu bilgiyi git işletim sisteminin environment veritabanından al




